---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  variable_files: 
    - "test/fixtures/tf_module/testing.tfvars"
  parallelism: 4

provisioner:
  name: terraform

platforms:
  - name: aws

verifier:
  name: awsspec
  format: progress #doc

suites:
  - name: "default"
    verifier:
      name: "awspec"
      patterns:
      - "test/integration/default/test_lambda.rb"
